disabled_rules:
  - file_length
  - function_parameter_count
  - nesting
  - opening_brace
  - unused_closure_parameter
  - unused_optional_binding
  - cyclomatic_complexity
  - function_body_length
  - line_length
opt_in_rules:
  - sorted_first_last
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - implicitly_unwrapped_optional
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - number_separator
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - private_outlet
  - redundant_nil_coalescing
  - vertical_parameter_alignment_on_call
  - untyped_error_in_catch
  - empty_string
  - empty_xctest_method
  - lower_acl_than_parent
  - modifier_order
  - static_operator
  - collection_alignment
  - identical_operands
  - toggle_bool
  - legacy_random
  - unused_import
  - unused_private_declaration
  - vertical_whitespace_between_cases
  - redundant_objc_attribute
  - multiline_arguments_brackets
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - nslocalizedstring_key
  - last_where
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - strong_iboutlet
  - xct_specific_matcher
  - trailing_closure
excluded:
  - Pods

type_name:
  max_length:
      warning: 50
      error: 60
modifier_order:
  preferred_modifier_order: [acl, override]
identifier_name:
  excluded:
    - id
    - to
trailing_comma:
  mandatory_comma: true
trailing_whitespace:
  ignores_empty_lines: true
trailing_closure:
  only_single_muted_parameter: true
large_tuple:
  warning: 3
  error: 4
deployment_target:
  iOS_deployment_target: 10
  tvOS_deployment_target: 10
  watchOS_deployment_target: 3
  macOS_deployment_target: 10.13
