os: osx
osx_image: xcode13
language: swift
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - PROJECT=FetchRequests.xcodeproj
    - RUN_TESTS="YES"
  matrix:
    - SCHEME="FetchRequests-iOS" DESTINATION="name=iPhone 12 Pro"
    - SCHEME="FetchRequests-tvOS" DESTINATION="name=Apple TV 4K (2nd generation)"
    - SCHEME="FetchRequests-watchOS" DESTINATION="name=Apple Watch Series 6 - 44mm"
    - SCHEME="FetchRequests-macOS" DESTINATION="arch=x86_64"
script:
  - set -o pipefail
  #- xcodebuild -version
  #- xcodebuild -showsdks
  - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=$RUN_TESTS test | xcpretty -c;
jobs:
  include:
    - stage: Pod Lint
      script:
        - pod lib lint --quick --fail-fast --verbose --skip-tests
    - stage: Example Project
      env:
        - SCHEME="iOS Example"
        - DESTINATION="name=iPhone 12 Pro"
        - PROJECT="Example/iOS-Example.xcodeproj"
      script:
        - set -o pipefail
        - xcodebuild -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty -c
after_success:
  - if [ $RUN_TESTS == "YES" ]; then
      bash <(curl -s https://codecov.io/bash);
    fi
