version: 2.1

executors:
  xcode:
    macos:
      xcode: 13.0.0
    environment:
      LC_CTYPE: en_US.UTF-8
      LANG: en_US.UTF-8

jobs:
  build:
    parameters:
      build-args:
        type: string
    executor: xcode
    parallelism: 4
    steps:
      - run:
          name: "Compile Library"
          command: xcodebuild -project "FetchRequests.xcodeproj" << parameters.build-args >> -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty -c
      - when:
          condition:
            and:
              - on_success
              - matches:
                  pattern: "^-scheme \"FetchRequests-iOS\""
                  value: << parameters.build-args >>
          steps:
            - run:
                name: "Pod Lint"
                command: pod lib lint --quick --fail-fast --verbose --skip-tests
            - run:
                name: "Compile Example Project"
                command: xcodebuild -project "Example/iOS-Example.xcodeproj" << parameters.build-args >> -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty -c
            #- run:
            #    name: Upload CodeCov.io Data
            #    command: bash <(curl -s https://codecov.io/bash)

workflows:
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              build-args:
                - "-scheme \"FetchRequests-iOS\" -destination \"name=iPhone 12 Pro\""
                - "-scheme \"FetchRequests-tvOS\" -destination \"name=Apple TV 4K (2nd generation)\""
                - "-scheme \"FetchRequests-watchOS\" -destination \"name=Apple Watch Series 6 - 44mm\""
                - "-scheme \"FetchRequests-macOS\" -destination \"arch=x86_64\""
